@MisuProject_HostAddress = http://localhost:5189


###
POST {{MisuProject_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "sai1@example.com",
  "password": "123456"


}


###
POST http://localhost:5189/api/follow/e44e0cc8-d96f-4eed-bb09-08ddc1f1f25e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiNThmMDFiNzItNjc1My00MmNkLWJiMGEtMDhkZGMxZjFmMjVlIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic2FpMUBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJVc2VyIiwiQWRtaW4iXSwiZXhwIjoxNzUyNjkyNTgyLCJpc3MiOiJNaXN1UHJvamVjdCIsImF1ZCI6Ik1pc3VQcm9qZWN0VXNlcnMifQ.lWyNN9GnJYGM7r17y0LnBKrybsRNICeNfaaMiTgn7KY

###
GET http://localhost:5189/api/follow/my-following
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiNThmMDFiNzItNjc1My00MmNkLWJiMGEtMDhkZGMxZjFmMjVlIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic2FpMUBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJVc2VyIiwiQWRtaW4iXSwiZXhwIjoxNzUyNjkzMTE0LCJpc3MiOiJNaXN1UHJvamVjdCIsImF1ZCI6Ik1pc3VQcm9qZWN0VXNlcnMifQ.7Z34Ujwu0efvmvAJJLSPUJyjUNLIoK6E1ZCArDE_jQw

###
GET http://localhost:5189/api/follow/my-followers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiNThmMDFiNzItNjc1My00MmNkLWJiMGEtMDhkZGMxZjFmMjVlIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic2FpMUBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJVc2VyIiwiQWRtaW4iXSwiZXhwIjoxNzUyNjkzMTE0LCJpc3MiOiJNaXN1UHJvamVjdCIsImF1ZCI6Ik1pc3VQcm9qZWN0VXNlcnMifQ.7Z34Ujwu0efvmvAJJLSPUJyjUNLIoK6E1ZCArDE_jQw

###
POST {{MisuProject_HostAddress}}/api/Auth/register

###
GET http://localhost:5189/api/auth/users